from django.contrib import admin
from django.urls import path
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('loginasstudent', views.loginasstudent, name='loginasstudent'),
    path('student/',views.student,name='student'),
    path('tstudent',views.tstudent,name='tstudent'),
    path('student_details/<str:student_eno>/<str:email_id>',views.student_details,name='student_details'),
    path('companylogin',views.companylogin,name='companylogin'),
    path('companydash',views.companydash,name='companydash'),
    path('tpologin',views.tpologin,name='tpologin'),
    path('registration',views.registration,name='registration'),
    path('sem_display',views.sem_display,name='sem_display'),
    path('mainregistration/<str:eno>/<str:email_id>/',views.mainregistration,name='mainregistration'),
    path('semester', views.semester, name='semester'),
    path('stuedntdashbord',views.stuedntdashbord,name='stuedntdashbord'), 
    path('prefrences',views.prefrences,name='prefrences'),
    path('companyRegi/',views.companyRegi,name='companyRegi'),
    path('companyReg2/', views.companyReg2, name='companyReg2'),
    path('internshipjob/<str:email_id>/<str:name>/',views.internshipjob,name='internshipjob'),
    path('rules',views.rules,name='rules'),
    path('tpodasboard/',views.tpodasboard,name='tpodasboard'),
    path('listjob',views.listjob,name='listjob'),
    path('detailsjob/<str:email_id>/<str:profile_name>/',views.detailsjob,name='detailsjob'),
    path('details/<str:email_id>/<str:profile_name>/',views.details,name='details'),
    path('jobApplication/', views.jobApplication, name='jobApplication'),
    path('applied_student/', views.applied_student, name='applied_student'),
    path('applied_jobs/', views.applied_student, name='applied_student'),
    path('profile/<int:student_id>/',views.profile, name='profile'),
    path('tprofile/<int:eno>/',views.tprofile, name='tprofile'),
    path('applied/',views.applied, name='applied'), 
    path('alumni_dashboard/',views.alumni_dashboard, name='alumni_dashboard'), 
    path('companypost/',views.companypost, name='companypost'),
    path('clogout/', views.clogout, name='clogout'),
    path('tlogout/', views.tlogout, name='tlogout'),
    path('slogout/', views.slogout, name='slogout'),
    path('tpoRegistration/', views.tpoRegistration, name='tpoRegistration'),
    path('tappliedStudent/', views.tappliedStudent, name='tappliedStudent'),
    path('registerStudent/', views.registerStudent, name='registerStudent'),
    path('tcompany/', views.tcompany, name='tcompany'),
    path('registerCompany/', views.registerCompany, name='registerCompany'),
    path('postjob/<str:email_id>/<str:name>/', views.postjob, name='postjob'),
    path('cregistration_profile/<str:email_id>/', views.cregistration_profile, name='cregistration_profile'),
    path('sregistration_profile/<str:eno>/', views.sregistration_profile, name='sregistration_profile'),
    path('registration_success/', views.registration_success, name='registration_success'),
    path('my_dashboard/', views.my_dashboard, name='my_dashboard'),
    path('approve_registration/<int:request_id>',views.approve_registration, name='approve_registration'),
    path('approve_Company/<str:request_id>',views.approve_Company, name='approve_Company'),
    path('approval_email/', views.approval_email,name='approval_email'),
    path('company_email_approval/', views.company_email_approval,name='company_email_approval'),
    path('disapprove_registration/<int:request_id>/', views.disapprove_registration, name='disapprove_registration'),
    path('disapprove_Company/<int:request_id>/', views.disapprove_Company, name='disapprove_Company'),  
    path('requestCompany/', views.requestCompany, name='requestCompany'), 
    path('RegisterAlumni/', views.RegisterAlumni, name='RegisterAlumni'),
    path('talumni/', views.talumni, name='talumni'),
    path('appliedAlumni/', views.appliedAlumni, name='appliedAlumni'),
    path('send_interview_email/', views.send_interview_email, name='send_interview_email'),
    path('selected_student/', views.selected_student, name='selected_student'),
    path('selected_candidate/', views.get_candidate, name='selected_candidate'),
    path('student_edit/', views.student_edit, name='student_edit'),
    path('edit_company/', views.edit_company, name='edit_company'),
    path('retrieve_computer_students/', views.retrieve_computer_students, name='retrieve_computer_students'),
    path('retrieve_IT_students/', views.retrieve_IT_students, name='retrieve_IT_students'),
    path('retrieve_CDDM_students/', views.retrieve_CDDM_students, name='retrieve_CDDM_students'),
    path('retrieve_Cvil_students/', views.retrieve_Cvil_students, name='retrieve_Cvil_students'),
    path('retrieve_EC_students/', views.retrieve_EC_students, name='retrieve_EC_students'),
    path('retrieve_Architecture_students/', views.retrieve_Architecture_students, name='retrieve_Architecture_students'),
    path('retrieve_Biomedical_students/', views.retrieve_Biomedical_students, name='retrieve_Biomedical_students'), 
    path('selected_total_student/', views.selected_total_student, name='selected_total_student'),
    path('contact/', views.contact, name='contact'),
    path('generate-pdf/', views.generate_pdf, name='generate_pdf'),
    path('rusume/', views.rusume, name='rusume'),    
    path('demo/', views.demo, name='demo'),
    path('get_demo/', views.get_demo, name='get_demo'),
    path('details_demo/<str:email_id>/<str:title>/', views.details_demo, name='details_demo'),
    path('approve_demo/<str:email_id>/<str:title>/', views.approve_demo, name='approve_demo'),
    path('disapprove_demo/<str:email_id>/<str:title>/', views.disapprove_demo, name='disapprove_demo'),    
        
    
       
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)